CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.BudgetLineItem (
    BudgetLineItemID INT AUTOINCREMENT PRIMARY KEY,
    BudgetHeaderID INT NOT NULL,
    GLAccountID INT NOT NULL,
    CostCenterID INT NOT NULL,
    FiscalPeriodID INT NOT NULL,
    OriginalAmount NUMBER(19,4) DEFAULT 0,
    AdjustedAmount NUMBER(19,4) DEFAULT 0,
    FinalAmount NUMBER(19,4) DEFAULT 0,
    SpreadMethodCode VARCHAR(50),
    EntryType VARCHAR(50),
    IsEliminated BOOLEAN DEFAULT FALSE,
    AllocationPercent NUMBER(5,2) DEFAULT 100,
    CreatedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
