CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.BudgetHeader (
    BudgetHeaderID INTEGER AUTOINCREMENT PRIMARY KEY,
    BudgetCode VARCHAR(50) NOT NULL,
    BudgetName VARCHAR(200) NOT NULL,
    BudgetType VARCHAR(20),
    ScenarioType VARCHAR(20),
    FiscalYear INTEGER NOT NULL,
    StartPeriodID INTEGER,
    EndPeriodID INTEGER,
    BaseBudgetHeaderID INTEGER,
    StatusCode VARCHAR(20),
    VersionNumber INTEGER DEFAULT 1,
    ExtendedProperties VARIANT,
    CreatedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ModifiedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (StartPeriodID) REFERENCES FINANCIAL_PLANNING.PLANNING.FiscalPeriod(FiscalPeriodID),
    FOREIGN KEY (EndPeriodID) REFERENCES FINANCIAL_PLANNING.PLANNING.FiscalPeriod(FiscalPeriodID),
    FOREIGN KEY (BaseBudgetHeaderID) REFERENCES FINANCIAL_PLANNING.PLANNING.BudgetHeader(BudgetHeaderID)
);
