CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.BudgetLineItem (
    BudgetLineItemID INTEGER AUTOINCREMENT PRIMARY KEY,
    BudgetHeaderID INTEGER NOT NULL,
    GLAccountID INTEGER NOT NULL,
    CostCenterID INTEGER NOT NULL,
    FiscalPeriodID INTEGER NOT NULL,
    OriginalAmount FLOAT DEFAULT 0,
    AdjustedAmount FLOAT DEFAULT 0,
    SpreadMethodCode VARCHAR(20),
    SourceSystem VARCHAR(50),
    IsAllocated BOOLEAN DEFAULT FALSE,
    LastModifiedByUserID INTEGER,
    LastModifiedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BudgetHeaderID) REFERENCES FINANCIAL_PLANNING.PLANNING.BudgetHeader(BudgetHeaderID),
    FOREIGN KEY (GLAccountID) REFERENCES FINANCIAL_PLANNING.PLANNING.GLAccount(GLAccountID),
    FOREIGN KEY (CostCenterID) REFERENCES FINANCIAL_PLANNING.PLANNING.CostCenter(CostCenterID),
    FOREIGN KEY (FiscalPeriodID) REFERENCES FINANCIAL_PLANNING.PLANNING.FiscalPeriod(FiscalPeriodID)
);
