CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.ConsolidationJournal (
    JournalID INT AUTOINCREMENT PRIMARY KEY,
    BudgetHeaderID INT NOT NULL,
    EntryType VARCHAR(50),
    Description VARCHAR(500),
    Amount NUMBER(19,4),
    CreatedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
