CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.CostCenter (
    CostCenterID INTEGER AUTOINCREMENT PRIMARY KEY,
    CostCenterCode VARCHAR(50) NOT NULL,
    CostCenterName VARCHAR(200) NOT NULL,
    ParentCostCenterID INTEGER,
    IsActive BOOLEAN DEFAULT TRUE,
    EffectiveFromDate DATE,
    EffectiveToDate DATE,
    CreatedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ModifiedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ParentCostCenterID) REFERENCES FINANCIAL_PLANNING.PLANNING.CostCenter(CostCenterID)
);
