CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.FiscalPeriod (
    FiscalPeriodID INT AUTOINCREMENT PRIMARY KEY,
    FiscalYear INT NOT NULL,
    FiscalQuarter INT NOT NULL,
    FiscalMonth INT NOT NULL,
    PeriodName VARCHAR(50),
    PeriodStartDate DATE NOT NULL,
    PeriodEndDate DATE NOT NULL,
    IsClosed BOOLEAN DEFAULT FALSE,
    IsAdjustmentPeriod BOOLEAN DEFAULT FALSE,
    CreatedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
