CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.FiscalPeriod (
    FiscalPeriodID INTEGER AUTOINCREMENT PRIMARY KEY,
    FiscalYear INTEGER NOT NULL,
    FiscalQuarter INTEGER,
    FiscalMonth INTEGER,
    PeriodName VARCHAR(50),
    PeriodStartDate DATE NOT NULL,
    PeriodEndDate DATE NOT NULL,
    IsClosed BOOLEAN DEFAULT FALSE,
    IsAdjustmentPeriod BOOLEAN DEFAULT FALSE,
    CreatedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ModifiedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
