CREATE TABLE IF NOT EXISTS FINANCIAL_PLANNING.PLANNING.GLAccount (
    GLAccountID INT AUTOINCREMENT PRIMARY KEY,
    AccountNumber VARCHAR(20) NOT NULL,
    AccountName VARCHAR(100) NOT NULL,
    AccountType VARCHAR(10),
    IsPostable BOOLEAN DEFAULT TRUE,
    IsBudgetable BOOLEAN DEFAULT TRUE,
    IntercompanyFlag BOOLEAN DEFAULT FALSE,
    NormalBalance VARCHAR(1),
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedDateTime TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
